CREATE TABLE IF NOT EXISTS users(
  uid INTEGER PRIMARY KEY,
  bx REAL DEFAULT 5,
  ton REAL DEFAULT 0,
  usdt REAL DEFAULT 0,
  mine_rate REAL DEFAULT 0.06,
  last_mine REAL DEFAULT 0,
  wd_today REAL DEFAULT 0,
  wd_day INTEGER DEFAULT 0,
  bnb REAL DEFAULT 0,
  sol REAL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS casino_logs(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uid INTEGER,
  game TEXT,
  bet REAL,
  result TEXT,
  ts REAL
);

CREATE TABLE IF NOT EXISTS usdt_orders(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uid INTEGER,
  provider TEXT,
  amount REAL,
  proof TEXT,
  status TEXT DEFAULT 'pending',
  ts REAL
);

CREATE TABLE IF NOT EXISTS analytics(
  k TEXT PRIMARY KEY,
  v REAL
);
